services:
  scid-web:
    build: .
    container_name: scid-web
    restart: unless-stopped

    mem_limit: 2g
    memswap_limit: 2g

    networks:
      - proxy

    volumes:
      - ./data:/opt/scid-web/data

networks:
  proxy:
    external: true
